# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f61e08c876fb0f1dbb1f1569fb8afcfd7d7238734e111f5d36229bb7ac78e7aa2cd5a8c8c965fcfb23c55cbe0ec28714aca63fd0e87bf4514cecf24105f7ecf

test:
  secret_key_base: a2fa693832c49304b641c97e643c69250fb5297d3736e1953e535f6b74fc4e1d8b8cd10386b2c551cb9c9a6aa1e8d9fb5ff8fee8cd877d20cfa3305120d461c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
